// frontend/libs/reactlib/components/welcome.tsx
import { getTodayDate } from '@nx-multi-stacks-monorepo/commonlib';
import styles from './welcome.module.scss';

/* eslint-disable-next-line */
export interface WelcomeProps {}

export function Welcome(props: WelcomeProps) {
  const today = getTodayDate().toDateString();
  return (
    <div className={styles['welcome']}>
      <h1>Welcome again, from <strong>reactlib!</strong></h1>
      <p>Today is: <strong>{today}</strong></p>
    </div>
  );
}

export default Welcome;

// frontend/libs/nglib/src/components/welcome.component.ts
import { ChangeDetectionStrategy, Component } from '@angular/core';
import { CommonModule } from '@angular/common';
import { getTodayDate } from '@nx-multi-stacks-monorepo/commonlib';

@Component({
  selector: 'nglib-welcome',
  standalone: true,
  imports: [CommonModule],
  templateUrl: './welcome.component.html',
  styleUrls: ['./welcome.component.scss'],
  changeDetection: ChangeDetectionStrategy.OnPush,
})
export class WelcomeComponent {
  today = getTodayDate();
}

<div class="welcome">
    <p>Welcome again, from <strong>nglib!</strong></p>
    <p>Today is: <strong>{{ today | date}}</strong></p>
</div>
